export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_SUCCCESS="GET_SUCCESS";
export const GET_FEEDING_DATA="GET_FEEDING_DATA";
export const USER_FEEDING_DATA="USER_FEEDING_DATA";